### ISSUE TITLE
(not logo request) Add content-creation / influencers category.

### ISSUE THREAD

**Issue by karol-depka** [gilbarbara/logos#629]
Hi.
I'm a big fan of svgporn :).

Since there wasn't another template for issues, i use this template. I hope it's ok.

Could a new category be added like "content creation" / "influencers" (right now the closest are video sharing and social network).
Examples: Instagram, YouTube, Twitch, etc. A category that would unify audio/video/photos/images sharing platforms in one category.
What do You think?

Thanks for Your consideration.
And thanks for all the great SVG logos :).
Best Wishes,
Karol

**Comment by karol-depka** [comment]
Also, is there a way/plan to have sub-categories?

(I also use SVGPorn as one of my ways to discover platforms/tools/products, etc., and sub-categories would be helpful)

**Comment by karol-depka** [comment]
Oh, I just noticed https://svgporn.com/#tag=content%20creators with Whalar. Wonder how/if this could be tied with things like YouTube, Twitch, etc. and the "influencers" keyword/category/concept.

**Comment by karol-depka** [comment]
Also found https://svgporn.com/#tag=influencer%20manager . Topic seems connected with content-creators too.

**Comment by gilbarbara** [comment]
Hey @karol-depka 

This repo is dedicated to providing logos for the tech community, which can be used for portfolios, presentations, stacks, and more.
So, I won’t add every social platform or related brand since many generic vector websites already cover those.
I’ve already rejected several “influencers” platforms’ logo requests since they are out of scope.

I haven’t touched categories for several years but I can add or update them. But with the restrictions I mentioned above, I don’t think the differentiation would matter much since there won’t be many new logos for these more specific categories.

As for the current "Social" category, are there any platforms that wouldn't fit under the "content creation" category?

I prefer to break down existing categories instead of adding sub-categories. Any suggestions?

Anyway, “Influencers” is not something that I care about. “Content creation” already covers this without the pejorative connotations.

**Comment by gilbarbara** [comment]
> Oh, I just noticed [svgporn.com/#tag=content%20creators](https://svgporn.com/#tag=content%20creators) with Whalar. Wonder how/if this could be tied with things like YouTube, Twitch, etc. and the "influencers" keyword/category/concept.

> Also found [svgporn.com/#tag=influencer%20manager](https://svgporn.com/#tag=influencer%20manager) . Topic seems connected with content-creators too.

Those are the rare exceptions.
Traackr and Whalar pivoted their business after I added them.

**Comment by karol-depka** [comment]
Hey @gilbarbara. Thank You for the reply and the explanation :). Appreciated :) !

Lemme think about what You wrote :). I will reply soon.
I know categories (or "ontologies":) ) can be a tricky topic ;).
